<!DOCTYPE html>
<html lang="en">
  <!-- Beautiful Jekyll | MIT license | Copyright Dean Attali 2016 -->
  <head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <title>LWKK</title>

  <meta name="author" content="LWKK" />

  

  <link rel="alternate" type="application/rss+xml" title="LWKK - Informatie van en over de werkgroep Kindermishandeling-Kinderartsen" href="/lwkk/feed.xml" />

  
    
      <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.0/css/font-awesome.min.css" />
    
  

  
    
      <link rel="stylesheet" href="/lwkk/css/bootstrap.min.css" />
    
      <link rel="stylesheet" href="/lwkk/css/bootstrap-social.css" />
    
      <link rel="stylesheet" href="/lwkk/css/main.css" />
    
  

  
    
      <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic" />
    
      <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800" />
    
  

  

  

  

    <!-- Facebook OpenGraph tags -->
  

  
  <meta property="og:title" content="LWKK" />
  

   
  <meta property="og:description" content="--- url: http://ArjanvK.github.io/lwkk baseurl: &quot;/lwkk&quot; title: LWKK description: Informatie van en over de werkgroep Kindermishandeling-Kinderartsen navbar-links: Over ons: aboutme Resources: - Beautiful Jekyll: http://deanattali.com/beautiful-jekyll/ - Learn markdown: http://www.markdowntutorial.com/ - GitHub Pages: https://pages.github.com/ Author's home: http://deanattali.com avatar: &quot;/img/avatar-icon.png&quot; author: name: LWKK email: lwkk.nvk@gmail.com facebook: yourname github: yourname twitter: yourname google-plus: &quot;+yourname&quot;...">
  


  <meta property="og:type" content="website" />

  
  <meta property="og:url" content="http://ArjanvK.github.io/lwkk/config-forestryio.yml" />
  <link rel="canonical" href="http://ArjanvK.github.io/lwkk/config-forestryio.yml" />
  

  
  <meta property="og:image" content="http://ArjanvK.github.io/lwkk/img/avatar-icon.png" />
  
  

  <!-- Twitter summary cards -->
  <meta name="twitter:card" content="summary" />
  <meta name="twitter:site" content="@yourname" />
  <meta name="twitter:creator" content="@yourname" />

  
  <meta name="twitter:title" content="LWKK" />
  

  
  <meta name="twitter:description" content="--- url: http://ArjanvK.github.io/lwkk baseurl: &quot;/lwkk&quot; title: LWKK description: Informatie van en over de werkgroep Kindermishandeling-Kinderartsen navbar-links: Over ons: aboutme Resources: - Beautiful Jekyll: http://deanattali.com/beautiful-jekyll/ - Learn markdown: http://www.markdowntutorial.com/ - GitHub Pages: https://pages.github.com/ Author's home: http://deanattali.com avatar: &quot;/img/avatar-icon.png&quot; author: name: LWKK email: lwkk.nvk@gmail.com facebook: yourname github: yourname twitter: yourname google-plus: &quot;+yourname&quot;...">
  

  
  <meta name="twitter:image" content="http://ArjanvK.github.io/lwkk/img/avatar-icon.png" />
  

</head>


  <body>
  
    <nav class="navbar navbar-default navbar-fixed-top navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="http://ArjanvK.github.io/lwkk">LWKK</a>
    </div>

    <div class="collapse navbar-collapse" id="main-navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
          <li>
            
            





<a href="/lwkk/aboutme">Over ons</a>

          </li>
        
        
        
          <li class="navlinks-container">
            <a class="navlinks-parent" href="javascript:void(0)">Resources</a>
            <div class="navlinks-children">
              
                
                  
            





<a href="http://deanattali.com/beautiful-jekyll/">Beautiful Jekyll</a>

                
              
                
                  
            





<a href="http://www.markdowntutorial.com/">Learn markdown</a>

                
              
                
                  
            





<a href="https://pages.github.com/">GitHub Pages</a>

                
              
            </div>
          </li>
        
        
        
          <li>
            
            





<a href="http://deanattali.com">Author's home</a>

          </li>
        
        
      </ul>
    </div>

	
	<div class="avatar-container">
	  <div class="avatar-img-border">
	    <a href="http://ArjanvK.github.io/lwkk ">
	      <img class="avatar-img" src="/lwkk/img/avatar-icon.png" />
		</a>
	  </div>
	</div>
	

  </div>
</nav>


    <!-- TODO this file has become a mess, refactor it -->


<div class="intro-header"></div>


<div class="container" role="main">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
      ---
url: http://ArjanvK.github.io/lwkk
baseurl: "/lwkk"
title: LWKK
description: Informatie van en over de werkgroep Kindermishandeling-Kinderartsen
navbar-links:
  Over ons: aboutme
  Resources:
  - Beautiful Jekyll: http://deanattali.com/beautiful-jekyll/
  - Learn markdown: http://www.markdowntutorial.com/
  - GitHub Pages: https://pages.github.com/
  Author's home: http://deanattali.com
avatar: "/img/avatar-icon.png"
author:
  name: LWKK
  email: lwkk.nvk@gmail.com
  facebook: yourname
  github: yourname
  twitter: yourname
  google-plus: "+yourname"
  linkedin: yourname
  xing: yourname
  stackoverflow: yourlink
  snapchat: yourname
  instagram: yourname
  youtube: yourlink
  spotify: yourname
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: false
  google-plus: false
  github: false
  linkedin: false
  xing: false
  stackoverflow: false
  snapchat: false
  instagram: false
  youtube: false
  spotify: false
share-links-active:
  twitter: false
  facebook: false
  google: false
  linkedin: false
url-pretty: artsennetkindermishandeling.nl
excerpt_length: 50
timezone: Europe/Amsterdam
markdown: kramdown
highlighter: rouge
permalink: "/:year-:month-:day-:title/"
paginate: 5
kramdown:
  input: GFM
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    comments: true
    social-share: true
- scope:
    path: ''
  values:
    layout: page
    show-avatar: true
link-tags: false
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
- Vagrantfile
prose:
  rooturl: _posts
  media: img
  ignore:
  - 404.html
  - LICENSE
  - feed.xml
  - _config.yml
  - "/_layouts"
  - "/_includes"
  - "/css"
  - "/img"
  - "/js"
  metadata:
    _posts:
    - name: layout
      field:
        element: hidden
        value: post
    - name: title
      field:
        element: text
        label: Post title
        placeholder: Title
        alterable: true
    - name: subtitle
      field:
        element: textarea
        label: Subtitle
        placeholder: A description of your post.
        alterable: true
    - name: date
      field:
        element: text
        label: Date
        help: Enter date of post.
        placeholder: yyyy-mm-dd
        alterable: true
    - name: published
      field:
        element: checkbox
        label: Publish
        help: Check to publish post, uncheck to hide.
gems:
- jekyll-paginate

	    
    </div>
  </div>
</div>


    <footer>
  <div class="container beautiful-jekyll-footer">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <ul class="list-inline text-center footer-links">
          
          
		  
      
		  
          <li>
            <a href="mailto:lwkk.nvk@gmail.com" title="Email me">
              <span class="fa-stack fa-lg">
                <i class="fa fa-circle fa-stack-2x"></i>
                <i class="fa fa-envelope fa-stack-1x fa-inverse"></i>
              </span>
            </a>
          </li>
          
		  
		  
		  
      
      
      
      
		  
        </ul>
        <p class="copyright text-muted">
		  LWKK
		  &nbsp;&bull;&nbsp;
		  2016

		  
		  &nbsp;&bull;&nbsp;
		  <a href="http://ArjanvK.github.io/lwkk">artsennetkindermishandeling.nl</a>
		  
	    </p>
	        <!-- Please don't remove this, keep my open source work credited :) -->
		<p class="theme-by text-muted">
		  Theme by
		  <a href="http://deanattali.com/beautiful-jekyll/">beautiful-jekyll</a>
		</p>
      </div>
    </div>
  </div>
</footer>

  
    






  
    <!-- doing something a bit funky here because I want to be careful not to include JQuery twice! -->
    
      <script>
      	if (typeof jQuery == 'undefined') {
      	  document.write('<script src="/lwkk/js/jquery-1.11.2.min.js"></scr' + 'ipt>');
      	}
      </script>
    
  
    <!-- doing something a bit funky here because I want to be careful not to include JQuery twice! -->
    
	<script src="/lwkk/js/bootstrap.min.js"></script>
    
  
    <!-- doing something a bit funky here because I want to be careful not to include JQuery twice! -->
    
	<script src="/lwkk/js/main.js"></script>
    
  




  
  </body>
</html>
